name: qr_code_scanner
description: events
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  js: ^0.6.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cloud_firestore: ^4.0.4
  firebase_core: ^2.1.1
  vibration: ^1.7.5


dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: net.touchcapture.qr.flutterqr
        pluginClass: FlutterQrPlugin
      ios:
        pluginClass: FlutterQrPlugin

